print ("1 გაკვეთლი")
print("niakabulahvili")
print("chiko")
print("charli")
print("miha")
print("gufi")
print("zoia")
print("giorgi")
print("nikolozi")
print("tiko")
print("pink 2გაკვეთლი")
print("dog gufi 3გაკვეთლი")
print("monkey,dog" )
print("მე ვცხოვრობ,ზღვის უბანი 11რაიონი 1კვარტალი კორპუსი ა საზარბაზო 1 ბინა 2 მე ვწავლობ სკოლაში თემქაზე 48 საჯარო სკოლა-ე მე ვწავლობ GOA-ში  5 გაკვეთილი")